export const InfoObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Air Transport Association 27',
    headLine: 'Flight Control: Aircraft Systems',
    description: 'Aircraft flight control systems consist of flight control surfaces, the respective cockpit controls, connecting linkages, and the necessary operating mechanisms to control an aircraft’s direction in flight.',
    description1: 'Airplane control systems are carefully designed to provide a natural feel, and at the same time, allow adequate responsiveness to control inputs.',
    description2: 'At low airspeeds, the controls usually feel soft and sluggish, and the airplane responds slowly to control applications.',
    description3: 'At high speeds, the controls feel firm and the response is more rapid.',
    imgStart: true,
    img: require('../../images/aircraft/sideview.png').default,
    alt: 'sideview',
    darkText: true,
};

export const InfoObjTwo = {
    id: 'control-system',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Mechanical Connections',
    headLine: 'Flight Control: Types',
    description: 'Mechanical are the most basic method of controlling an aircraft. They were used in early aircraft and are currently used in small aircraft where the aerodynamic forces are not excessive.',
    description1: 'Hydro-mechanical are complex and the weight of a mechanical flight control systems increase considerably with the size and performance of the aircraft.',
    description2: 'Fly-by-wire is a flight control system that replaces the physical connection between pilot controls and the flight control surfaces with an electrical interface. In addition, in some large and fast aircraft, controls are boosted by hydraulically or electrically actuated systems. In both the fly-by-wire and boosted controls, the feel of the control reaction is fed back to the pilot by simulated means.',
    imgStart: false,
    img: require('../../images/aircraft/isometric.png').default,
    alt: 'isometric',
    darkText: true,
};

export const InfoObjThree = {
    id: 'primary',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Maneuverability',
    headLine: 'Flight Control: Primary',
    description: 'Ailerons control nose about the longitudinal axis. The ailerons are attached to the outboard trailing edge of each wing and move in the opposite direction from each other.',
    description1: "Elevators are usually at the rear of an aircraft which controls the aircraft's pitch.",
    description2: 'A Rudder is a vertical airfoil pivoted from the horizontal stabilizer of an aircraft; for contnoseing movement around the vertical axis.',
    imgStart: true,
    img: require('../../images/aircraft/frontview.png').default,
    alt: 'frontview',
    darkText: false,
};

export const InfoObjFour = {
    id: 'secondary',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'High Lift Devices',
    headLine: 'Flight Control: Secondary',
    description: 'In aircraft design, high-lift devices are moving surfaces or stationary components intended to increase lift during certain flight conditions.',
    description1: 'Most jet transport aircraft are fitted with high lift devices on both leading and trailing edges which increase the lift coefficients to enable the aircraft to generate large amounts of lift at low speed for take-off and landing. Smaller aircraft are usually just fitted with trailing edge flaps.',
    description2: 'Aircraft are fitted with high lift devices to reduce the take-off and landing distances.',
    imgStart: false,
    img: require('../../images/aircraft/topview.png').default,
    alt: 'topview',
    darkText: false,
};

export const InfoObjFive = {
    id: 'flaps',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Increase Lifts',
    headLine: 'Secondary Control: Flaps',
    description: 'Plain flap increases the lift by approximately 55 %. Split edge flap increases the lift by approximately 65 %. Slotted flaps increase the lift by approximately 70 %. Fowler flap increases the lift by approximately 90 %.',
    description1: '',
    description2: '',
    description3: '',
    imgStart: true,
    img: require('../../images/aircraft/sideview.png').default,
    alt: 'sideview',
    darkText: true,
};

export const InfoObjSix = {
    id: 'leading-edge',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'High Lift Devices',
    headLine: 'Flight Control: Leading Edge Devices',
    description: 'The slat or slot may be either full span, or may occur on only part of the wing (usually outboard), depending on how the lift characteristics need to be modified for good low speed control.',
    description1: 'Krueger flap is apart of the lower surface of the leading edge, which can be rotated about its forward edge.',
    description2: 'Spoilers are deployed from the wings to spoil the smooth airflow, reducing lift and increasing drag.',
    description3: 'An airplane is trimmed when it will maintain its attitude and speed without the pilot having to apply any load to the cockpit controls.',
    imgStart: false,
    img: require('../../images/aircraft/isometric.png').default,
    alt: 'isometric',
    darkText: false,
};

// Model Data Objects Onward

export const InfoObjSeven = {
    id: 'nose',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Horizontal Tail Interaction',
    headLine: 'Elevator: Pitch',
    description: '',
    description1: '',
    description2: '',
    description3: '',
    imgStart: false,
    img: require('../../images/model/pitch.gif').default,
    alt: 'nose',
    darkText: false,
}

export const InfoObjEight = {
    id: 'roll',
    lightBg: false,
    lightText: true, 
    lightTextDesc: true,
    topLine: 'Wings Interaction',
    headLine: 'Ailerons: Roll',
    description: '',
    description1: '',
    description2: '',
    description3: '',
    imgStart: true,
    img: require('../../images/model/roll.gif').default,
    alt: 'roll',
    darkText: false,
}

export const InfoObjNine = {
    id: 'rudder',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Vertical Tail Interaction',
    headLine: 'Rudder: Yaw',
    description: '',
    description1: '',
    description2: '',
    description3: '',
    imgStart: false,
    img: require('../../images/model/rudder.gif').default,
    alt: 'rudder',
    darkText: false,
}